name: open_data_air_traffic
version: "1.0"
config-version: 2

profile: open_data_air_traffic

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  open_data_air_traffic:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    quality:
      +materialized: view
    marts:
      +materialized: table
